[terminal.shell]
program = "/usr/bin/zsh"


[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 9.0

[window]
opacity = 0.9
padding = {x = 8 , y = 8}


[colors.primary]
background = "#201F26"


[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
]
